services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # assuming frontend Dockerfile serves on port 80 (nginx)
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data: